In [1]:
# install library to connect python with mysql
!pip install mysql-connector-python

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mysql-connector-python in c:\users\shiks\appdata\roaming\python\python313\site-packages (9.6.0)

In [2]:
# import the basic packages
import numpy as np

import pandas as pd

import seaborn as sns

import matplotlib.pyplot as plt
%matplotlib inline

import warnings 
warnings.filterwarnings(action = "ignore")

In [3]:
# import mysql connector for the connection
import mysql.connector

In [4]:
conn = mysql.connector.connect(
    # create connection to mysql database
    
    host="localhost",
    # database is on local machine
    
    user="root",
    # mysql username
    
    password="Shiksha@1017",
    # mysql password
    
    database="big_mart"
    # database name to connect
    
    )

In [5]:
query = "select * from cleaned_bigmart ;"
# sql query to get all data from the table

In [6]:
df = pd.read_sql(query, conn)
# load data from mysql into a pandas dataFrame

# here, query tells what data to fetch from mysql, and conn tells from where to fetch the data

In [7]:
# view
df.head()

,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,Outlet_Age
0,9.30,Low Fat,0.016047,Dairy,249.8092,1999,Medium,Tier 1,Supermarket Type1,3735.1380,25
1,5.92,Regular,0.019278,Soft Drinks,48.2692,2009,Medium,Tier 3,Supermarket Type2,443.4228,15
2,17.50,Low Fat,0.016760,Meat,141.6180,1999,Medium,Tier 1,Supermarket Type1,2097.2700,25
3,19.20,Regular,0.066132,Fruits and Vegetables,182.0950,1998,Medium,Tier 3,Grocery Store,732.3800,26
4,8.93,Low Fat,0.066132,Household,53.8614,1987,High,Tier 3,Supermarket Type1,994.7052,37

In [8]:
# building model, seperating x and y

x = df.drop("Item_Outlet_Sales", axis = 1)

y = df.Item_Outlet_Sales

In [9]:
# verify
x[:1]

,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Outlet_Age
0,9.3,Low Fat,0.016047,Dairy,249.8092,1999,Medium,Tier 1,Supermarket Type1,25

In [10]:
# shape of x
x.shape

(8523, 10)

In [11]:
# and
y[:1]

0    3735.138
Name: Item_Outlet_Sales, dtype: float64

In [12]:
# shape of y
y.shape

(8523,)

In [13]:
x = pd.get_dummies(x, drop_first=True)

In [14]:
x[:2]

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Establishment_Year,Outlet_Age,Item_Fat_Content_Regular,Item_Type_Breads,Item_Type_Breakfast,Item_Type_Canned,Item_Type_Dairy,...,Item_Type_Snack Foods,Item_Type_Soft Drinks,Item_Type_Starchy Foods,Outlet_Size_Medium,Outlet_Size_Small,Outlet_Location_Type_Tier 2,Outlet_Location_Type_Tier 3,Outlet_Type_Supermarket Type1,Outlet_Type_Supermarket Type2,Outlet_Type_Supermarket Type3
0,9.30,0.016047,249.8092,1999,25,False,False,False,False,True,...,False,False,False,True,False,False,False,True,False,False
1,5.92,0.019278,48.2692,2009,15,True,False,False,False,False,...,False,True,False,True,False,False,True,False,True,False

In [15]:
# checking shape
x.shape

(8523, 28)

In [16]:
# checking data type
x.dtypes

Item_Weight                        float64
Item_Visibility                    float64
Item_MRP                           float64
Outlet_Establishment_Year            int64
Outlet_Age                           int64
Item_Fat_Content_Regular              bool
Item_Type_Breads                      bool
Item_Type_Breakfast                   bool
Item_Type_Canned                      bool
Item_Type_Dairy                       bool
Item_Type_Frozen Foods                bool
Item_Type_Fruits and Vegetables       bool
Item_Type_Hard Drinks                 bool
Item_Type_Health and Hygiene          bool
Item_Type_Household                   bool
Item_Type_Meat                        bool
Item_Type_Others                      bool
Item_Type_Seafood                     bool
Item_Type_Snack Foods                 bool
Item_Type_Soft Drinks                 bool
Item_Type_Starchy Foods               bool
Outlet_Size_Medium                    bool
Outlet_Size_Small                     bool
Outlet_Location_Type_Tier 2           bool
Outlet_Location_Type_Tier 3           bool
Outlet_Type_Supermarket Type1         bool
Outlet_Type_Supermarket Type2         bool
Outlet_Type_Supermarket Type3         bool
dtype: object

In [17]:
# checking data type of y
y.dtypes

dtype('float64')

In [18]:
# train_test_split
from sklearn.model_selection import train_test_split

In [19]:
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size = 0.2 , random_state = 1)

In [20]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((6818, 28), (1705, 28), (6818,), (1705,))

In [21]:
# model building
from sklearn.linear_model import LinearRegression

In [22]:
# call and assign
lr = LinearRegression()

In [23]:
# fit the model
lr.fit(x_train, y_train)

LinearRegression()

In [24]:
# train accuracy
lr.score(x_train, y_train)

0.5642043052818086

In [25]:
# test accuracy
lr.score(x_test, y_test)

0.558227347421568

In [26]:
# prediction
y_pred = lr.predict(x_test)

In [27]:
# view
df.head()

,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,Outlet_Age
0,9.30,Low Fat,0.016047,Dairy,249.8092,1999,Medium,Tier 1,Supermarket Type1,3735.1380,25
1,5.92,Regular,0.019278,Soft Drinks,48.2692,2009,Medium,Tier 3,Supermarket Type2,443.4228,15
2,17.50,Low Fat,0.016760,Meat,141.6180,1999,Medium,Tier 1,Supermarket Type1,2097.2700,25
3,19.20,Regular,0.066132,Fruits and Vegetables,182.0950,1998,Medium,Tier 3,Grocery Store,732.3800,26
4,8.93,Low Fat,0.066132,Household,53.8614,1987,High,Tier 3,Supermarket Type1,994.7052,37

In [28]:
from sklearn.metrics import r2_score, mean_absolute_error

In [29]:
# ----- Evaluation -----
print("R2 Score:", r2_score(y_test, y_pred))

R2 Score: 0.558227347421568

In [30]:
# scaling the data
from sklearn.preprocessing import StandardScaler

In [31]:
scaler = StandardScaler()

In [32]:
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [33]:
lr.fit(x_train_scaled,y_train)

LinearRegression()

In [34]:
lr.score(x_train_scaled,y_train)

0.5642043052818086

In [35]:
lr.score(x_test_scaled,y_test)

0.5582273474215678

In [36]:
# dataset
x

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Establishment_Year,Outlet_Age,Item_Fat_Content_Regular,Item_Type_Breads,Item_Type_Breakfast,Item_Type_Canned,Item_Type_Dairy,...,Item_Type_Snack Foods,Item_Type_Soft Drinks,Item_Type_Starchy Foods,Outlet_Size_Medium,Outlet_Size_Small,Outlet_Location_Type_Tier 2,Outlet_Location_Type_Tier 3,Outlet_Type_Supermarket Type1,Outlet_Type_Supermarket Type2,Outlet_Type_Supermarket Type3
0,9.300,0.016047,249.8092,1999,25,False,False,False,False,True,...,False,False,False,True,False,False,False,True,False,False
1,5.920,0.019278,48.2692,2009,15,True,False,False,False,False,...,False,True,False,True,False,False,True,False,True,False
2,17.500,0.016760,141.6180,1999,25,False,False,False,False,False,...,False,False,False,True,False,False,False,True,False,False
3,19.200,0.066132,182.0950,1998,26,True,False,False,False,False,...,False,False,False,True,False,False,True,False,False,False
4,8.930,0.066132,53.8614,1987,37,False,False,False,False,False,...,False,False,False,False,False,False,True,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8518,6.865,0.056783,214.5218,1987,37,False,False,False,False,False,...,True,False,False,False,False,False,True,True,False,False
8519,8.380,0.046982,108.1570,2002,22,True,False,False,False,False,...,False,False,False,True,False,True,False,True,False,False
8520,10.600,0.035186,85.1224,2004,20,False,False,False,False,False,...,False,False,False,False,True,True,False,True,False,False
8521,7.210,0.145221,103.1332,2009,15,True,False,False,False,False,...,True,False,False,True,False,False,True,False,True,False
8522,14.800,0.044878,75.4670,1997,27,False,False,False,False,False,...,False,True,False,False,True,False,False,True,False,False

In [37]:
# Scaling does not improve the accuracy
# use regularization models

In [38]:
from sklearn.linear_model import Ridge

In [39]:
ridge = Ridge()

In [40]:
ridge.fit(x_train,y_train)

Ridge()

In [41]:
ridge.score(x_train,y_train)

0.5641844161043208

In [42]:
ridge.score(x_test,y_test)

0.5582239503012589

In [43]:
ridge.fit(x_train_scaled,y_train)

Ridge()

In [44]:
ridge.score(x_train_scaled,y_train)

0.5642036888829991

In [45]:
ridge.score(x_test_scaled,y_test)

0.5582200751731632

In [46]:
y_pred = ridge.predict(x_test_scaled)

In [47]:
r2_score(y_test,y_pred)

0.5582200751731632

In [48]:
ridge = Ridge(alpha=0.01)

In [49]:
ridge.fit(x_train,y_train)

Ridge(alpha=0.01)

In [50]:
ridge.score(x_train,y_train)

0.564204302660076

In [51]:
ridge.score(x_test,y_test)

0.5582273188861011

In [52]:
ridge.fit(x_train_scaled,y_train)

Ridge(alpha=0.01)

In [53]:
ridge.score(x_test_scaled,y_test)

0.5582272720224019

In [54]:
from sklearn.linear_model import Lasso

In [55]:
lasso = Lasso()

In [56]:
lasso.fit(x_train,y_train)

Lasso()

In [57]:
lasso.score(x_train,y_train)

0.5636346729691414

In [58]:
lasso.score(x_test,y_test)

0.5584950742726881

In [59]:
lasso.fit(x_train_scaled,y_train)

Lasso()

In [60]:
lasso.score(x_train_scaled,y_train)

0.563929414215627

In [61]:
lasso.score(x_test_scaled,y_test)

0.5578577680328093

In [62]:
lasso =Lasso(alpha=0.01)

In [63]:
lasso.fit(x_train,y_train)

Lasso(alpha=0.01)

In [64]:
lasso.score(x_train,y_train)

0.5642041733156271

In [65]:
lasso.score(x_test,y_test)

0.5582311523759288

In [66]:
lasso.fit(x_train_scaled,y_train)

Lasso(alpha=0.01)

In [67]:
lasso.score(x_train_scaled,y_train)

0.564204268572414

In [68]:
lasso.score(x_test_scaled,y_test)

0.5582255976120813

In [69]:
from sklearn.metrics import mean_squared_error

There is no change in accuracy so using XGBOOST Regressor

In [70]:
pip install xgboost

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: xgboost in c:\users\shiks\appdata\roaming\python\python313\site-packages (3.2.0)
Requirement already satisfied: numpy in c:\programdata\anaconda3\lib\site-packages (from xgboost) (2.3.5)
Requirement already satisfied: scipy in c:\programdata\anaconda3\lib\site-packages (from xgboost) (1.16.3)
Note: you may need to restart the kernel to use updated packages.

In [71]:
# train_test_split
from sklearn.model_selection import train_test_split

In [72]:
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size = 0.2 , random_state = 1)

In [73]:
# model building
from xgboost import XGBRegressor

In [74]:
xgb = XGBRegressor(n_estimators=200, learning_rate=0.05, max_depth=4, subsample=0.8, colsample_bytree=0.8, reg_alpha=0.3, reg_lambda=1, random_state=42)

In [75]:
# fit the model
xgb.fit(x_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=4,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=200,
             n_jobs=None, num_parallel_tree=None, ...)

In [76]:
# train accuracy
xgb.score(x_train, y_train)

0.6622669642497381

In [77]:
# test accuracy
xgb.score(x_test, y_test)

0.5838525469530165

In [78]:
# prediction
y_pred = xgb.predict(x_test)

In [79]:
from sklearn.metrics import r2_score, mean_absolute_error

In [80]:
print("R2 Score:", r2_score(y_test, y_pred))

R2 Score: 0.5838525469530165

In [81]:
print("MAE:", mean_absolute_error(y_test, y_pred))

MAE: 779.8924102076601

In [82]:
# now, push full data to mysql

In [88]:
from sqlalchemy import create_engine
# is used to connect python with the database and transfer data

In [ ]:
engine = create_engine(
    "mysql+mysqlconnector://<root_name>:<YOUR_MYSQL_PASSWORD>@localhost/big_mart"
)

In [90]:
# at first, create connection engine
# then use mysql with mysqlconnector driver and provide username, password, host (local machine), database name

In [91]:
# df.to_sql("cleaned_bigmart", con = engine, if_exists = 'replace', index = False)

In [92]:
engine.connect()

In [93]:
# alternative, if we don’t want to replace
df.to_sql("bigmart_with_predictions", con = engine, if_exists = 'replace', index = False)

8523

In [94]:
# send dataframe to mysql, name of the table to create / store data, use database connection, 

# replace table if it already exists,  do not store dataframe index as column

In [95]:
# custom predictions: hold